<h1>Contact</h1>

<form action="" method="post">
    <div class="form-group">
        <label for="subject">Subject</label>
        <input type="text" name="subject" class="form-control">
    </div>
    <div class="form-group">
        <label for="email">Email</label>
        <input type="email" name="email" class="form-control">
    </div>
    <div class="form-group">
        <label for="body">Body</label>
        <textarea name="body" class="form-control"></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>