<?php
/** @var $this \nazares\decoracore\View */
/** @var $model \app\models\ContactForm */

use nazares\decoracore\form\TextareaField;

$this->title = 'Contact';
?>

<h1>Contact</h1>

<?php $form = \nazares\decoracore\form\Form::begin('', 'post'); ?>
<?php echo $form->field($model, 'subject'); ?>
<?php echo $form->field($model, 'email'); ?>
<?php echo new TextareaField($model, 'body') ?>
<button type="submit" class="btn btn-primary">Submit</button>
<?php \nazares\decoracore\form\Form::end(); ?>
