<h1>Register</h1>
<form action="" method="post">
    <div class="form_field">
        <label for="subject">Subject</label>
        <input type="text" name="subject">
    </div>
    <div class="form_field">
        <label for="email">Email</label>
        <input type="email" name="email">
    </div>
    <div class="form_field">
        <label for="body">Body</label>
        <textarea name="body" id="" cols="30" rows="10"></textarea>
    </div>
    <button type="submit">Send</button>
</form>