<?php
/** @var $this \nazares\decoracore\View */
/** @var $model \app\models\User */
$this->title = 'Registration';
?>

<h1>Register</h1>

<?php $form =  \nazares\decoracore\form\Form::begin('', 'post') ?>
<div class="row">
    <div class="col">
        <?php echo $form->field($model, 'firstname') ?>
    </div>
    <div class="col">
        <?php echo $form->field($model, 'lastname') ?>
    </div>
</div>

<?php echo $form->field($model, 'email') ?>
<?php echo $form->field($model, 'password')->passwordField() ?>
<?php echo $form->field($model, 'confirmPassword')->passwordField() ?>
<button type="submit" class="btn btn-primary">Submit</button>
<?php \nazares\decoracore\form\Form::end() ?>